version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynamic-pricing-api
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Add other environment variables as needed
    ports:
      - "8000:8000"
    depends_on:
      - redis 