INSERT INTO agent_decisions (product_id, agent_name, decision_type, input_data, output_data, confidence_score, explanation, reflection, reasoning_chain, timestamp) VALUES
('P1001', 'PricingDecisionAgent', 'price_increase', '{"demand_score": 0.85, "inventory_level": 120, "competitor_prices": [18.99, 19.99], "base_price": 15.99}', '{"new_price": 17.99, "change_percentage": 12.5}', 0.95, 'Increased price due to high demand and competitive positioning', 'The decision to increase price was justified by strong demand signals and competitor pricing. However, I should monitor if this affects sales velocity.', '{"step1": "Analyzed demand score of 0.85", "step2": "Checked inventory level of 120 units", "step3": "Compared with competitor prices", "step4": "Applied pricing strategy", "step5": "Finalized new price"}', '2024-06-01 10:00:00'),
('P1002', 'PricingDecisionAgent', 'price_increase', '{"demand_score": 0.92, "inventory_level": 80, "competitor_prices": [52.99, 48.99], "base_price": 45.00}', '{"new_price": 49.99, "change_percentage": 11.1}', 0.98, 'Premium product with excellent demand justifies price increase', 'The premium positioning and high demand score support this price increase. The product maintains competitive advantage while maximizing profit margins.', '{"step1": "Evaluated premium market position", "step2": "Assessed high demand score of 0.92", "step3": "Analyzed competitor premium pricing", "step4": "Calculated optimal price point", "step5": "Applied premium pricing strategy"}', '2024-06-01 10:05:00'),
('P1003', 'DemandAnalysisAgent', 'demand_assessment', '{"sales_velocity": 15.7, "price_elasticity": -1.5, "stock_level": 200}', '{"demand_score": 0.78, "trend": "stable", "recommendation": "maintain_price"}', 0.87, 'High sales velocity indicates strong demand despite budget positioning', 'The high sales velocity suggests the product is performing well in its budget segment. The negative price elasticity indicates price sensitivity.', '{"step1": "Calculated sales velocity from recent data", "step2": "Analyzed price elasticity impact", "step3": "Assessed market segment performance", "step4": "Determined demand score", "step5": "Generated recommendations"}', '2024-06-01 10:10:00'),
('P1004', 'InventoryTrackingAgent', 'stock_assessment', '{"current_stock": 150, "reorder_point": 40, "max_stock": 250}', '{"status": "healthy", "recommendation": "no_action", "days_until_reorder": 15}', 0.92, 'Stock levels are healthy and above reorder point', 'Current inventory levels are optimal. The system predicts 15 days until reorder point is reached based on current sales velocity.', '{"step1": "Checked current stock level", "step2": "Compared with reorder point", "step3": "Calculated days until reorder", "step4": "Assessed inventory health", "step5": "Generated recommendations"}', '2024-06-01 10:15:00'),
('P1005', 'CompetitorMonitoringAgent', 'price_analysis', '{"competitor_prices": [29.99], "our_price": 27.99, "market_position": "premium"}', '{"price_advantage": 2.00, "recommendation": "maintain_position", "confidence": 0.89}', 0.89, 'Maintaining competitive advantage in premium segment', 'Our price is competitive in the premium segment. The $2 advantage provides good margin while maintaining market position.', '{"step1": "Gathered competitor price data", "step2": "Calculated price advantage", "step3": "Assessed market positioning", "step4": "Evaluated competitive landscape", "step5": "Generated strategic recommendations"}', '2024-06-01 10:20:00');

-- Dummy data for feedback_log table
INSERT INTO feedback_log (agent_name, feedback_type, message, related_product_id, timestamp)
VALUES
  ('PricingDecisionAgent', 'reflection', 'Price was set too high, consider lowering next cycle.', 'P12345', '2024-07-02T12:00:00Z'),
  ('SupervisorAgent', 'manual_review', 'Manual override required for product P12345.', 'P12345', '2024-07-02T13:00:00Z'); 